services:
  redis:
    image: redis:7-alpine
    container_name: qafila_redis
    ports:
      - "6379:6379"
    networks:
      - qafila_network

  kafka:
    image: bitnami/kafka:3.7
    container_name: qafila_kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    networks:
      - qafila_network

  api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    container_name: qafila_fastapi
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka:9092
    depends_on:
      - redis
      - kafka
    networks:
      - qafila_network

networks:
  qafila_network:
    driver: bridge
